version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=max
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # alternative setup
    # build:
    #   context: ./backend
    #   # only need to include dockerfile cmd if not named dockerfile
    #   dockerfile: Dockerfile
        # args:
        #   some-arg: 1
    ports: 
      - '80:80'   
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    
    
  # frontend:

volumes:
  data:
  logs:
    